name: Polaris Gate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  polaris-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Black Duck Security Scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          polaris_server_url: ${{ vars.POLARIS_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_application_name: 'break-build-test'
          polaris_project_name: 'break-build-test'
          polaris_assessment_types: 'SAST'
          polaris_prComment_enabled: true
          polaris_prComment_severities: 'CRITICAL,HIGH,MEDIUM'
          mark_build_status: 'failure'
          github_token: ${{ secrets.GITHUB_TOKEN }}
